### ISSUE TITLE
codelf does not show up with correct height.

### ISSUE THREAD

**Issue by zhaocai** [unbug/atom-codelf#2]
## Screenshot

[atom-codelf height issue screen clip](http://www.evernote.com/l/AA-i1B02iU9GL7QpssvLOjSk5b7MxSaOlRk/)

**Comment by unbug** [comment]
Yeah, it's an issue in the latest Atom, working on it

**Comment by unbug** [comment]
The issue was fixed in V3.2.5+ :)
